# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-OuctqKXkRpOvCIsdp_fSngd90P6MWKi
"""

pip install streamlit pandas plotly-express financial-sentiment-risk

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import plotly.express as px
# from financial_sentiment_risk import FinancialSentimentRiskAnalyzer
# 
# # Initialize the model
# @st.cache_resource
# def load_analyzer():
#     return FinancialSentimentRiskAnalyzer()
# 
# analyzer = load_analyzer()
# 
# # Page Configuration
# st.set_page_config(page_title="FinSense Dashboard", layout="wide")
# 
# st.title("📊 Financial Sentiment & Risk Analyzer")
# st.markdown("---")
# 
# # Sidebar for Input
# with st.sidebar:
#     st.header("Input Panel")
#     input_text = st.text_area("Paste financial text (earnings, news, reports):", height=300)
#     analyze_button = st.button("Run Full Analysis", type="primary")
# 
# if analyze_button and input_text:
#     # Run the model
#     with st.spinner('Analyzing financial signals...'):
#         result = analyzer.analyze(input_text)
# 
#     # --- Top Row: Summary & Sentiment ---
#     col1, col2, col3 = st.columns([2, 1, 1])
# 
#     with col1:
#         st.subheader("Summary")
#         st.info(result.summary)
# 
#     with col2:
#         st.metric("Sentiment Score", f"{result.sentiment.compound:+.2f}", result.sentiment.label)
#         st.write(f"Confidence: {result.sentiment.confidence:.1%}")
# 
#     with col3:
#         st.metric("Overall Risk", result.risk.overall_risk, f"Score: {result.risk.risk_score}/10", delta_color="inverse")
# 
#     st.divider()
# 
#     # --- Second Row: Risk Categories & Entities ---
#     col_risk, col_entity = st.columns(2)
# 
#     with col_risk:
#         st.subheader("🔴 Risk Distribution")
#         if result.risk.risk_categories:
#             risk_df = pd.DataFrame(list(result.risk.risk_categories.items()), columns=['Category', 'Score'])
#             fig = px.bar(risk_df, x='Score', y='Category', orientation='h', color='Score', color_continuous_scale='Reds')
#             st.plotly_chart(fig, use_container_width=True)
#         else:
#             st.write("No specific risk categories detected.")
# 
#     with col_entity:
#         st.subheader("🏷 Extracted Entities")
#         tabs = st.tabs(["Companies", "Values", "Metrics", "Dates"])
#         tabs[0].write(", ".join(result.entities.companies) if result.entities.companies else "None")
#         tabs[1].write(", ".join(result.entities.monetary_values) if result.entities.monetary_values else "None")
#         tabs[2].write(", ".join(result.entities.financial_metrics) if result.entities.financial_metrics else "None")
#         tabs[3].write(", ".join(result.entities.dates) if result.entities.dates else "None")
# 
#     st.divider()
# 
#     # --- Third Row: Market Signals & Implications ---
#     col_sig, col_impl = st.columns(2)
# 
#     with col_sig:
#         st.subheader("📡 Market Signals")
#         for signal in result.market_signals:
#             st.write(signal)
# 
#     with col_impl:
#         st.subheader("💼 Investment Implications")
#         for impl in result.investment_implications:
#             st.success(impl)
# 
# else:
#     st.info("Paste a financial report or news snippet in the sidebar to begin analysis.")

!streamlit run app.py

pip install streamlit